name: Build Android APK

on:
  workflow_dispatch:  # allows manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd vite-project
          npm install

      - name: Build web app
        run: |
          cd vite-project
          npm run build

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Capacitor + Android
        run: |
          cd vite-project
          npm install @capacitor/core @capacitor/cli
          npx cap add android

      - name: Build Android APK
        run: |
          cd vite-project/android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightwave-unsigned-apk
          path: vite-project/android/app/build/outputs/apk/debug/app-debug.apk
